import { brandPalette, hexToRgba, modernSlatePalette } from '@/shared/styles/palette';
import type { SemanticColorToken } from './tokens.config';

type ThemeColorScale = Record<SemanticColorToken, string>;

const modernSlateLight = {
  background: modernSlatePalette.background,
  foreground: modernSlatePalette.text,
  heading: modernSlatePalette.heading,
  card: modernSlatePalette.surface,
  cardForeground: modernSlatePalette.text,
  popover: modernSlatePalette.surface,
  popoverForeground: modernSlatePalette.text,
  primary: modernSlatePalette.primary,
  primaryHover: modernSlatePalette.primaryHover,
  primaryForeground: '#FFFFFF',
  secondary: modernSlatePalette.sidebarHover,
  secondaryForeground: modernSlatePalette.text,
  muted: modernSlatePalette.surfaceSubtle,
  mutedForeground: modernSlatePalette.textSecondary,
  accent: modernSlatePalette.primarySoft,
  accentForeground: modernSlatePalette.primary,
  destructive: modernSlatePalette.error,
  destructiveForeground: '#FFFFFF',
  border: modernSlatePalette.border,
  divider: modernSlatePalette.divider,
  input: modernSlatePalette.border,
  ring: modernSlatePalette.primary,
  info: modernSlatePalette.info,
  success: modernSlatePalette.success,
  warning: modernSlatePalette.warning,
  error: modernSlatePalette.error,
  surfaceSubtle: modernSlatePalette.surfaceSubtle,
  surfaceMuted: modernSlatePalette.surfaceMuted,
  textSubtle: modernSlatePalette.textSecondary,
  focus: modernSlatePalette.primary,
  overlay: hexToRgba(modernSlatePalette.heading, 0.42),
  inverseSurface: modernSlatePalette.heading,
  inverseForeground: '#FFFFFF',
  inverseBorder: 'rgba(255, 255, 255, 0.16)',
  disabled: '#F3F4F6',
  disabledForeground: modernSlatePalette.disabled,
  infoBg: modernSlatePalette.infoSoft,
  successBg: modernSlatePalette.successSoft,
  warningBg: modernSlatePalette.warningSoft,
  errorBg: modernSlatePalette.errorSoft,
} satisfies ThemeColorScale;

export const themeColors = {
  light: modernSlateLight,
  modern: modernSlateLight,
  dark: {
    background: '#0F172A',
    foreground: '#E5E7EB',
    heading: '#F9FAFB',
    card: '#111827',
    cardForeground: '#E5E7EB',
    popover: '#1F2937',
    popoverForeground: '#E5E7EB',
    primary: '#8299FF',
    primaryHover: '#8EA2FF',
    primaryForeground: '#0F172A',
    secondary: '#1E293B',
    secondaryForeground: '#E5E7EB',
    muted: '#172033',
    mutedForeground: '#94A3B8',
    accent: '#18244C',
    accentForeground: '#A5B4FC',
    destructive: '#F87171',
    destructiveForeground: '#111827',
    border: '#334155',
    divider: '#263548',
    input: '#334155',
    ring: modernSlatePalette.primaryHover,
    info: '#38BDF8',
    success: '#4ADE80',
    warning: '#FBBF24',
    error: '#F87171',
    surfaceSubtle: '#172033',
    surfaceMuted: '#1E293B',
    textSubtle: '#94A3B8',
    focus: modernSlatePalette.primaryHover,
    overlay: 'rgba(2, 6, 23, 0.72)',
    inverseSurface: '#020617',
    inverseForeground: '#F8FAFC',
    inverseBorder: 'rgba(255, 255, 255, 0.16)',
    disabled: '#1E293B',
    disabledForeground: '#64748B',
    infoBg: '#0C2840',
    successBg: '#143C2A',
    warningBg: '#443015',
    errorBg: '#481F25',
  },
  claude: {
    background: '#FAFAF8',
    foreground: '#1F1F1E',
    heading: '#1F1F1E',
    card: '#FFFFFF',
    cardForeground: '#1F1F1E',
    popover: '#FFFFFF',
    popoverForeground: '#1F1F1E',
    primary: '#AD4E36',
    primaryHover: '#B95A40',
    primaryForeground: '#FFFFFF',
    secondary: '#E7E5E4',
    secondaryForeground: '#1F1F1E',
    muted: '#F5F5F4',
    mutedForeground: '#78716C',
    accent: '#FDEEE8',
    accentForeground: '#AD4E36',
    destructive: '#B91C1C',
    destructiveForeground: '#FFFFFF',
    border: '#E7E5E4',
    divider: '#EEEDE9',
    input: '#E7E5E4',
    ring: '#D97757',
    info: '#1D4ED8',
    success: '#047857',
    warning: '#B45309',
    error: '#B91C1C',
    surfaceSubtle: '#FAFAF8',
    surfaceMuted: '#F5F5F4',
    textSubtle: '#78716C',
    focus: '#D97757',
    overlay: hexToRgba(brandPalette.black, 0.38),
    inverseSurface: '#1F1F1E',
    inverseForeground: '#FAFAF8',
    inverseBorder: '#E7E5E4',
    disabled: '#F5F5F4',
    disabledForeground: '#A8A29E',
    infoBg: '#EFF6FF',
    successBg: '#ECFDF5',
    warningBg: '#FEF3C7',
    errorBg: '#FEE2E2',
  },
} satisfies Record<string, ThemeColorScale>;

export type ThemeMode = keyof typeof themeColors;
export type ThemeColors = ThemeColorScale;

export const DEFAULT_THEME: ThemeMode = 'modern';
