
export const HTTP_ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  EMAIL_REQUIRED: 'AUTH_EMAIL_REQUIRED',
  EMAIL_INVALID: 'AUTH_EMAIL_INVALID',
  PASSWORD_REQUIRED: 'AUTH_PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'AUTH_PASSWORD_MIN_LENGTH',
  PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  IDENTIFIER_REQUIRED: 'AUTH_IDENTIFIER_REQUIRED',
  RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  RESET_TOKEN_REQUIRED: 'AUTH_RESET_TOKEN_REQUIRED',
  RESET_PASSWORD_FAILED: 'AUTH_RESET_PASSWORD_FAILED',
  FORGOT_PASSWORD_SUCCESS: 'AUTH_FORGOT_PASSWORD_SUCCESS',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_INACTIVE: 'USER_INACTIVE',
} as const;

export const VALIDATION_ERROR_CODES = {
  ERROR: 'VALIDATION_ERROR',
  FAILED: 'VALIDATION_FAILED',
  REQUIRED: 'VALIDATION_REQUIRED',
  INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  MIN_LENGTH: 'VALIDATION_MIN_LENGTH',
  MAX_LENGTH: 'VALIDATION_MAX_LENGTH',
  MIN_VALUE: 'VALIDATION_MIN_VALUE',
  MAX_VALUE: 'VALIDATION_MAX_VALUE',
  EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  PHONE_INVALID: 'VALIDATION_PHONE_INVALID',
  DATE_INVALID: 'VALIDATION_DATE_INVALID',
  DUPLICATE: 'VALIDATION_DUPLICATE',
} as const;

export const RESOURCE_ERROR_CODES = {
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  CONFLICT: 'RESOURCE_CONFLICT',
  CREATE_FAILED: 'RESOURCE_CREATE_FAILED',
  UPDATE_FAILED: 'RESOURCE_UPDATE_FAILED',
  DELETE_FAILED: 'RESOURCE_DELETE_FAILED',
  FETCH_FAILED: 'RESOURCE_FETCH_FAILED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  OPTIMISTIC_LOCK_CONFLICT: 'OPTIMISTIC_LOCK_CONFLICT',
} as const;

export const FILE_ERROR_CODES = {
  NOT_FOUND: 'FILE_NOT_FOUND',
  TOO_LARGE: 'FILE_TOO_LARGE',
  TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  DELETE_FAILED: 'FILE_DELETE_FAILED',
} as const;

export const EXTERNAL_ERROR_CODES = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
} as const;

export const GENERIC_ERROR_CODES = {
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export const ERROR_CODES = {
  ...HTTP_ERROR_CODES,
  ...AUTH_ERROR_CODES,
  ...VALIDATION_ERROR_CODES,
  ...RESOURCE_ERROR_CODES,
  ...FILE_ERROR_CODES,
  ...EXTERNAL_ERROR_CODES,
  ...GENERIC_ERROR_CODES,
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
