import { PERMISSION_ACTIONS as ACTIONS, PERMISSION_SUBJECTS, permissionKey } from '@/shared/rbac';

export const PERMISSION_ACTIONS = Object.values(ACTIONS);

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export const COMMON_PERMISSIONS = {
  USERS_READ: permissionKey(PERMISSION_SUBJECTS.USERS, ACTIONS.READ),
  USERS_CREATE: permissionKey(PERMISSION_SUBJECTS.USERS, ACTIONS.CREATE),
  USERS_UPDATE: permissionKey(PERMISSION_SUBJECTS.USERS, ACTIONS.UPDATE),
  USERS_DELETE: permissionKey(PERMISSION_SUBJECTS.USERS, ACTIONS.DELETE),
  USERS_MANAGE: permissionKey(PERMISSION_SUBJECTS.USERS, ACTIONS.MANAGE),

  ROLES_READ: permissionKey(PERMISSION_SUBJECTS.ROLES, ACTIONS.READ),
  ROLES_CREATE: permissionKey(PERMISSION_SUBJECTS.ROLES, ACTIONS.CREATE),
  ROLES_UPDATE: permissionKey(PERMISSION_SUBJECTS.ROLES, ACTIONS.UPDATE),
  ROLES_DELETE: permissionKey(PERMISSION_SUBJECTS.ROLES, ACTIONS.DELETE),
  ROLES_MANAGE: permissionKey(PERMISSION_SUBJECTS.ROLES, ACTIONS.MANAGE),

  PERMISSIONS_READ: permissionKey(PERMISSION_SUBJECTS.PERMISSIONS, ACTIONS.READ),
  PERMISSIONS_CREATE: permissionKey(PERMISSION_SUBJECTS.PERMISSIONS, ACTIONS.CREATE),
  PERMISSIONS_UPDATE: permissionKey(PERMISSION_SUBJECTS.PERMISSIONS, ACTIONS.UPDATE),
  PERMISSIONS_DELETE: permissionKey(PERMISSION_SUBJECTS.PERMISSIONS, ACTIONS.DELETE),
  PERMISSIONS_MANAGE: permissionKey(PERMISSION_SUBJECTS.PERMISSIONS, ACTIONS.MANAGE),

  MEDIA_READ: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.READ),
  MEDIA_CREATE: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.CREATE),
  MEDIA_UPDATE: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.UPDATE),
  MEDIA_DELETE: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.DELETE),
  MEDIA_UPLOAD: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.UPLOAD),
  MEDIA_MANAGE: permissionKey(PERMISSION_SUBJECTS.MEDIA, ACTIONS.MANAGE),

  MESSAGES_READ: permissionKey(PERMISSION_SUBJECTS.MESSAGES, ACTIONS.READ),
  MESSAGES_CREATE: permissionKey(PERMISSION_SUBJECTS.MESSAGES, ACTIONS.CREATE),
  MESSAGES_UPDATE: permissionKey(PERMISSION_SUBJECTS.MESSAGES, ACTIONS.UPDATE),
  MESSAGES_DELETE: permissionKey(PERMISSION_SUBJECTS.MESSAGES, ACTIONS.DELETE),
  MESSAGES_MANAGE: permissionKey(PERMISSION_SUBJECTS.MESSAGES, ACTIONS.MANAGE),
} as const;
